### ISSUE TITLE
Provide a way to unpublish content for archiving purposes

### ISSUE THREAD

**Issue by jhung** [inclusive-design/idrc#170]
## Is your feature request related to a problem? Please describe.

It may be useful to provide a way to unpublish content and keep the content for archival purposes.

Currently when you unpublish content, it will appear in the Workflow with "Ready", "In Review", or "Draft" status which can clutter the interface from pages that are actively being worked on.

## Describe the solution you'd like

Add a 4th workflow status "Hidden", "Archived" or "Unpublished Archive".

## Additional context

Encountered this issue when cleaning up the staff pages and unpublished staff who have moved on from the IDRC.

**Comment by jobara** [comment]
Perhaps this thread will help. https://github.com/11ty/eleventy/issues/1123

There may be a way to mark up the post so that you can remove, or rather not add, it to the collection.  However, this probably won't affect the Netlify CMS workflows. I'd assume it would still appear published but with an archived flag. Which likely causes a different type of clutter.

For the staff pages, at least at the moment, it's probably easier to just remove them outright and rely on version control. Are there other or more complex examples that we may want to "temporarily" archive?

**Comment by TheDocTrier** [comment]
I left a comment on the previously referenced 11ty/eleventy#1123, but I'll mentioned it here. I created [TheDocTrier/eleventy-plugin-ignore](https://github.com/TheDocTrier/eleventy-plugin-ignore) to allow you to programmatically ignore files from the eleventy build based on their front matter. I have not tested it inside a CMS such as Netlify, but it may work for you.
