### ISSUE TITLE
Add Get Involved page

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/idrc#80]

**Comment by cherylhjli** [comment]
After trying this page with photos, I realized we sadly just don't have enough nice photos to cut it.
Going back to the version where things are in columns (now 2 instead of 3) - https://www.figma.com/file/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=76%3A2050

Ideally, after the visual design is flushed out, it'd be nice to have illustrations on top of the headings, just FYI in case this changes anything - 
https://www.figma.com/file/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=592%3A65
